config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: %i[index create show] do
    resources :bookmarks, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, :list, presence: true, uniqueness: { scope: %i[movie list] }
  validates :comment, length: { minimum: 6 }, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to root_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def show
    @bookmark = Bookmark.new
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class='header'>
    <div class = 'header-text'>
      <h1>Personnal Watchlist</h1>
      <div>
        <p>Store, comment and recommend your favorites movies !</p>
      </div>
    </div>
  </div>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="cards mt-5">

  <% @lists.each do |list| %>
    <% if list.movies.exists? %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.movies.sample[:poster_url]%>)">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% else %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTA4tXENtPf8nswNh6cVc1JejrIy2V6L0n_-g&usqp=CAU"%>)">
          <%= link_to list.name, list_path(list) %>
        </div>
    <% end %>
  <% end %>

</div>



<hr>


<div class="form-card">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name, label: 'Provide the name of the new list'%>
    <%= f.button :button, class: "form-btn" do %>
        Create a list
    <% end %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="show-container">
  <h1><%= @list.name %></h1>
  <hr>

  <div class="cards">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-product">
        <img src=<%= bookmark.movie[:poster_url]%> />
        <div class="card-product-infos">
          <h2><%= bookmark.movie.title %></h2>
          <p><%= bookmark.comment %></p>
          <%= link_to list_bookmark_path(@list,bookmark), data: {turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?"} do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <hr>


  <div class="form-card mb-5">
    <%= simple_form_for([@list, @bookmark]) do |f| %>
      <%= f.association :movie, label: 'Please select a movie from the list' %>
      <%= f.input :comment, label: 'Provide us a comment for this bookmark' %>
      <%= f.button :button, class: "form-btn" do %>
        Create a bookmark
    <% end %>
    <% end %>
  </div>
  <%= link_to 'Back to index', root_path, class: "back-btn" %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>